services:
  db:
    build: docker/mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ""
      MYSQL_USER: root
      MYSQL_DB: ""
    container_name: db
  php:
    build: docker/php
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf/default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
    links:
      - db
    container_name: php
